let id = 0;

export const projects = {
  c: {
    libft: {
      id:(id += 1),
      title: 'Libft',
      tags: ['c'],
      content: 'Part of libC',
      githubLink: '#',
      size: 1,
      dateOf: 2014,
      categorie: 'c',
      tryIt: false,
    },
    get_next_line: {
      id:(id += 1),
      title: 'Get_next_line',
      tags: ['c'],
      content: 'Like readline',
      githubLink: '#',
      size: 1,
      dateOf: 2014,
      categorie: 'c',
      tryIt: false,
    },
    printf: {
      id:(id += 1),
      title: 'Printf',
      tags: ['c'],
      content: 'Like printf',
      githubLink: '#',
      size: 2,
      dateOf: 2016,
      categorie: 'c',
      tryIt: false,
    },
    pushSwap: {
      id:(id += 1),
      title: 'Push swap',
      tags: ['c'],
      content: 'Sorting project with two stack. Then goal is to use both stack to return one stack with all sorted value',
      githubLink: '#',
      size: 2,
      dateOf: 2015,
      categorie: 'c',
      tryIt: false,
    },
    sh: {
      id:(id += 1),
      title: '42sh',
      tags: ['c', 'unix'],
      content: 'A commande line interpreter & builtins (like Bash) with Tercamps Lib',
      githubLink: '#',
      size: 10,
      dateOf: 2015,
      categorie: 'c',
      tryIt: false,
    },
    nmOtool: {
      id:(id += 1),
      title: 'Nm/Otool',
      tags: ['c', 'unix'],
      content: 'Like nm & otool command (nm: listing symbol of binary, otool: displays  specified  parts  of  object  files  or libraries)',
      githubLink: '#',
      size: 5,
      dateOf: 2015,
      categorie: 'c',
      tryIt: false,
    },
  },

  python: {
    taskMaster: {
      id:(id += 1),
      title: 'Task Master',
      tags: ['python','unix'],
      content: 'Process gestionair like supervisor',
      githubLink: '#',
      size: 2,
      dateOf: 2016,
      categorie: 'python',
      tryIt: false,
    },
    facebookTerminal: {
      id:(id += 1),
      title: 'Facebook Terminal',
      tags: ['python'],
      content: 'Basic fb python scrapper and message sender/checker',
      githubLink: '#',
      size: 2,
      dateOf: 2016,
      categorie: 'python',
      tryIt: false,
    },
  },

  web: {
    roshambo: {
      id: (id += 1),
      title: 'Rock Paper Scissor',
      tags: ['react', 'javascript'],
      content: 'Rock paper scissor versus computer who select shape randomly',
      githubLink: '#',
      size: 1,
      dateOf: 2017,
      categorie: 'web',
      tryIt: true,
    },
    marvelCatalog: {
      id: (id += 1),
      title: 'Marvel Catalog',
      tags: ['react', 'javascript'],
      content: 'Catalog of marvel Heroes with character sheet',
      githubLink: '#',
      size: 1,
      dateOf: 2017,
      categorie: 'web',
      tryIt: true,
    },
    todoList: {
      id: (id += 1),
      title: 'Todo list',
      tags: ['react', 'javascript', 'node', 'mongo'],
      content: 'Todo list with task and multi-user gestion with socket',
      githubLink: '#',
      size: 5,
      dateOf: 2017,
      categorie: 'web',
      tryIt: true,
    },
    myWebSite: {
      id: (id += 1),
      title: 'My website',
      tags: ['react', 'javascript'],
      content: 'This Website , full react with redux and functional programming with Ramda librairy: www.ramdajs.com. And ant design graphic library: https://ant.design/',
      githubLink: '#',
      size: 3,
      dateOf: 2017,
      categorie: 'web',
      tryIt: false,
    },
    phpPool: {
      id: (id += 1),
      title: 'PHP pool',
      tags: ['php', 'html/css', 'sql'],
      content: '2 weeks of web learning about PHP, SQL db, html/css, and one day about javascript and jquery ',
      githubLink: '#',
      size: 2,
      dateOf: 2016,
      categorie: 'web',
      tryIt: false,
    },
  },

  security: {
    rootMeAppSystem: {
      id:(id += 1),
      title: 'Root me App/system',
      tags: ['c', 'unix', 'python', 'asm'],
      content: 'Series of challenge from plateform www.root-me.org in categorie App/system. Login credentials are provided for different challenge, the goal is to obtain additional rights by exploiting program’s weaknesses and get a password to validate challs on the portal.',
      githubLink: '#',
      size: 10,
      dateOf: 2016,
      categorie: 'security',
      tryIt: false,
    },
    rootMeAppScript: {
      id:(id += 1),
      title: 'Root me App/script',
      tags: ['unix', 'python'],
      content: 'You will have credentials for each challenge. The goal is to leverage your privileges by exploiting some environment vulnerabilities (incorrect permissions on files, weak encryption, ...) and some development mistakes.',
      githubLink: '#',
      size: 4,
      dateOf: 2016,
      categorie: 'security',
      tryIt: false,
    },
    rootMeWeb: {
      id:(id += 1),
      title: 'Root me Web Server/Client',
      tags: ['javascript', 'php', 'webTools', 'sql'],
      content: 'Series of challenge from plateform www.root-me.org in categorie web server and web client',
      githubLink: '#',
      size: 8,
      dateOf: 2016,
      categorie: 'security',
      tryIt: false,
    },
    rootMeSteganographie: {
      id:(id += 1),
      title: 'Root me Steganographie',
      tags: ['unix', 'webTools'],
      content: 'Series of challenge from plateform www.root-me.org in categorie Steganographie (Art of concealment)',
      githubLink: '#',
      size: 3,
      dateOf: 2016,
      categorie: 'security',
      tryIt: false,
    },
    snowCrash: {
      id:(id += 1),
      title: 'SnowCrash',
      tags: ['unix', 'c', 'python', 'lua'],
      content: 'Series of challenge on VM. Get the flag level to level up',
      githubLink: '#',
      size: 5,
      dateOf: 2016,
      categorie: 'security',
      tryIt: false,
    },
  },
};

export const tagColors = {
  c: 'orange',
  python: 'blue',
  unix: 'grey',
  react: 'red',
  javascript: 'yellow',
  node: 'purple',
  php: 'green',
  'html/css': 'darkgreen',
  sql: 'cadetblue',
  asm: 'lightgrey',
  lua: 'brown',
  webTools: 'wheat',
  mongo: 'gold',
}

export const tags = [
  'c',
  'python',
  'unix',
  'react',
  'javascript',
  'node',
  'php',
  'html/css',
  'sql',
  'asm',
  'lua',
  'webTools',
  'mongo',
]

export const titleStyle = {
  c: {
    color: 'darkorange',
    icon: 'code'
  },
  web: {
    color: 'seagreen',
    icon: 'global'
  },
  python: {
    color: 'cornflowerblue',
    icon: 'tool'
  },
  security: {
    color: 'black',
    icon: 'key'
  },
}
